# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c6ZdDRRx66rc9ZYX13hZa7TUjzYSCMYN
"""

# Define a function to print Hello, World!
def print_hello():
    print("Hello, World!")

# Call the function
print_hello()

# Use a for loop to print Hello, World!
for i in range(1):
    print("Hello, World!")

# Use a while loop to print Hello, World!
count = 0
while count < 1:
    print("Hello, World!")
    count += 1

# Using lambda function
hello_lambda = lambda: print("Hello, World!")
hello_lambda()

# Use a class to print Hello, World!
class Greeter:
    def greet(self):
        print("Hello, World!")

# Create an instance of the class and call the method
greeter = Greeter()
greeter.greet()

# Final print
print("Hello, World! Done.")