# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHhMmn53pWypeR3uc0RaZY6p_eXVwxvB
"""

# 1. Print a greeting
print("Hello, World!")

# 2. Create variables
name = "Google Colab"
year = 2024

# 3. Print variables
print("Welcome to", name)
print("The current year is:", year)

# 4. Basic math operation
a = 10
b = 20
sum_ab = a + b
print("The sum of", a, "and", b, "is:", sum_ab)

# 5. Create a list
fruits = ["apple", "banana", "cherry"]

# 6. Print list elements
print("Fruits list:", fruits)

# 7. Add item to list
fruits.append("orange")
print("Updated fruits list:", fruits)

# 8. Loop through the list
for fruit in fruits:
    print("I like", fruit)